
const data = {
  name: "Ecommecer",
  isFolder: true,
  items: [
    {
      id_menu: 2,
      menu_name: "Quản lý người dùng",
      id_parent: 0,
      icon: "users",
      slug: "/accout",
      active: 1,
      permission: [
        {
          id_permission: 1,
          permission_key: "view",
          permission_name: "Xem",
          icon: "eye",
        },
      ],
    },
    {
      id_menu: 3,
      menu_name: "Danh sách nhân viên",
      id_parent: 2,
      icon: "arrow-right",
      slug: "/acc/employees",
      active: 1,
      permission: [
        {
          id_permission: 1,
          permission_key: "view",
          permission_name: "Xem",
          icon: "eye",
        },
        {
          id_permission: 2,
          permission_key: "refresh",
          permission_name: "Làm mới",
          icon: "refresh-cw",
        },
        {
          id_permission: 3,
          permission_key: "create",
          permission_name: "Thêm mới",
          icon: "plus",
        },
        {
          id_permission: 4,
          permission_key: "update",
          permission_name: "Chỉnh sửa",
          icon: "edit-3",
        },
        {
          id_permission: 5,
          permission_key: "active",
          permission_name: "Hoạt động",
          icon: "check",
        },
        {
          id_permission: 6,
          permission_key: "unactive",
          permission_name: "Tạm ngưng",
          icon: "x",
        },
        {
          id_permission: 7,
          permission_key: "delete",
          permission_name: "Xóa",
          icon: "trash",
        },
        {
          id_permission: 8,
          permission_key: "exportExcel",
          permission_name: "Excel",
          icon: "file",
        },
        {
          id_permission: 9,
          permission_key: "filter",
          permission_name: "Lọc",
          icon: "filter",
        },
      ],
    },
    {
      id_menu: 40,
      menu_name: "Hợp đồng lao động",
      id_parent: 2,
      icon: "arrow-right",
      slug: "/acc/contract",
      active: 1,
      permission: [
        {
          id_permission: 1,
          permission_key: "view",
          permission_name: "Xem",
          icon: "eye",
        },
        {
          id_permission: 2,
          permission_key: "refresh",
          permission_name: "Làm mới",
          icon: "refresh-cw",
        },
        {
          id_permission: 3,
          permission_key: "create",
          permission_name: "Thêm mới",
          icon: "plus",
        },
        {
          id_permission: 4,
          permission_key: "update",
          permission_name: "Chỉnh sửa",
          icon: "edit-3",
        },
        {
          id_permission: 5,
          permission_key: "active",
          permission_name: "Hoạt động",
          icon: "check",
        },
        {
          id_permission: 6,
          permission_key: "unactive",
          permission_name: "Tạm ngưng",
          icon: "x",
        },
        {
          id_permission: 7,
          permission_key: "delete",
          permission_name: "Xóa",
          icon: "trash",
        },
        {
          id_permission: 8,
          permission_key: "exportExcel",
          permission_name: "Excel",
          icon: "file",
        },
        {
          id_permission: 9,
          permission_key: "filter",
          permission_name: "Lọc",
          icon: "filter",
        },
      ],
    },
    {
      id_menu: 34,
      menu_name: "Loại hợp đồng",
      id_parent: 2,
      icon: "arrow-right",
      slug: "/acc/contract-type",
      active: 1,
      permission: [
        {
          id_permission: 1,
          permission_key: "view",
          permission_name: "Xem",
          icon: "eye",
        },
        {
          id_permission: 2,
          permission_key: "refresh",
          permission_name: "Làm mới",
          icon: "refresh-cw",
        },
        {
          id_permission: 3,
          permission_key: "create",
          permission_name: "Thêm mới",
          icon: "plus",
        },
        {
          id_permission: 4,
          permission_key: "update",
          permission_name: "Chỉnh sửa",
          icon: "edit-3",
        },
        {
          id_permission: 5,
          permission_key: "active",
          permission_name: "Hoạt động",
          icon: "check",
        },
        {
          id_permission: 6,
          permission_key: "unactive",
          permission_name: "Tạm ngưng",
          icon: "x",
        },
        {
          id_permission: 7,
          permission_key: "delete",
          permission_name: "Xóa",
          icon: "trash",
        },
        {
          id_permission: 8,
          permission_key: "exportExcel",
          permission_name: "Excel",
          icon: "file",
        },
        {
          id_permission: 9,
          permission_key: "filter",
          permission_name: "Lọc",
          icon: "filter",
        },
      ],
    },
    {
      id_menu: 31,
      menu_name: "Chức danh",
      id_parent: 2,
      icon: "arrow-right",
      slug: "/acc/position",
      active: 1,
      permission: [
        {
          id_permission: 1,
          permission_key: "view",
          permission_name: "Xem",
          icon: "eye",
        },
        {
          id_permission: 2,
          permission_key: "refresh",
          permission_name: "Làm mới",
          icon: "refresh-cw",
        },
        {
          id_permission: 3,
          permission_key: "create",
          permission_name: "Thêm mới",
          icon: "plus",
        },
        {
          id_permission: 4,
          permission_key: "update",
          permission_name: "Chỉnh sửa",
          icon: "edit-3",
        },
        {
          id_permission: 5,
          permission_key: "active",
          permission_name: "Hoạt động",
          icon: "check",
        },
        {
          id_permission: 6,
          permission_key: "unactive",
          permission_name: "Tạm ngưng",
          icon: "x",
        },
        {
          id_permission: 7,
          permission_key: "delete",
          permission_name: "Xóa",
          icon: "trash",
        },
        {
          id_permission: 8,
          permission_key: "exportExcel",
          permission_name: "Excel",
          icon: "file",
        },
        {
          id_permission: 9,
          permission_key: "filter",
          permission_name: "Lọc",
          icon: "filter",
        },
      ],
    },
    {
      id_menu: 40,
      menu_name: "Hợp đồng lao động",
      id_parent: 2,
      icon: "arrow-right",
      slug: "/acc/contract",
      active: 1,
      permission: [
        {
          id_permission: 1,
          permission_key: "view",
          permission_name: "Xem",
          icon: "eye",
        },
        {
          id_permission: 2,
          permission_key: "refresh",
          permission_name: "Làm mới",
          icon: "refresh-cw",
        },
        {
          id_permission: 3,
          permission_key: "create",
          permission_name: "Thêm mới",
          icon: "plus",
        },
        {
          id_permission: 4,
          permission_key: "update",
          permission_name: "Chỉnh sửa",
          icon: "edit-3",
        },
        {
          id_permission: 5,
          permission_key: "active",
          permission_name: "Hoạt động",
          icon: "check",
        },
        {
          id_permission: 6,
          permission_key: "unactive",
          permission_name: "Tạm ngưng",
          icon: "x",
        },
        {
          id_permission: 7,
          permission_key: "delete",
          permission_name: "Xóa",
          icon: "trash",
        },
        {
          id_permission: 8,
          permission_key: "exportExcel",
          permission_name: "Excel",
          icon: "file",
        },
        {
          id_permission: 9,
          permission_key: "filter",
          permission_name: "Lọc",
          icon: "filter",
        },
      ],
    },
    {
      id_menu: 34,
      menu_name: "Loại hợp đồng",
      id_parent: 2,
      icon: "arrow-right",
      slug: "/acc/contract-type",
      active: 1,
      permission: [
        {
          id_permission: 1,
          permission_key: "view",
          permission_name: "Xem",
          icon: "eye",
        },
        {
          id_permission: 2,
          permission_key: "refresh",
          permission_name: "Làm mới",
          icon: "refresh-cw",
        },
        {
          id_permission: 3,
          permission_key: "create",
          permission_name: "Thêm mới",
          icon: "plus",
        },
        {
          id_permission: 4,
          permission_key: "update",
          permission_name: "Chỉnh sửa",
          icon: "edit-3",
        },
        {
          id_permission: 5,
          permission_key: "active",
          permission_name: "Hoạt động",
          icon: "check",
        },
        {
          id_permission: 6,
          permission_key: "unactive",
          permission_name: "Tạm ngưng",
          icon: "x",
        },
        {
          id_permission: 7,
          permission_key: "delete",
          permission_name: "Xóa",
          icon: "trash",
        },
        {
          id_permission: 8,
          permission_key: "exportExcel",
          permission_name: "Excel",
          icon: "file",
        },
        {
          id_permission: 9,
          permission_key: "filter",
          permission_name: "Lọc",
          icon: "filter",
        },
      ],
    },
    {
      id_menu: 31,
      menu_name: "Chức danh",
      id_parent: 2,
      icon: "arrow-right",
      slug: "/acc/position",
      active: 1,
      permission: [
        {
          id_permission: 1,
          permission_key: "view",
          permission_name: "Xem",
          icon: "eye",
        },
        {
          id_permission: 2,
          permission_key: "refresh",
          permission_name: "Làm mới",
          icon: "refresh-cw",
        },
        {
          id_permission: 3,
          permission_key: "create",
          permission_name: "Thêm mới",
          icon: "plus",
        },
        {
          id_permission: 4,
          permission_key: "update",
          permission_name: "Chỉnh sửa",
          icon: "edit-3",
        },
        {
          id_permission: 5,
          permission_key: "active",
          permission_name: "Hoạt động",
          icon: "check",
        },
        {
          id_permission: 6,
          permission_key: "unactive",
          permission_name: "Tạm ngưng",
          icon: "x",
        },
        {
          id_permission: 7,
          permission_key: "delete",
          permission_name: "Xóa",
          icon: "trash",
        },
        {
          id_permission: 8,
          permission_key: "exportExcel",
          permission_name: "Excel",
          icon: "file",
        },
        {
          id_permission: 9,
          permission_key: "filter",
          permission_name: "Lọc",
          icon: "filter",
        },
      ],
    },
  ],
};
export default data;



